# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 48
    bpp: 8
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F042B",  # mdi-printer-3d
      "\U000F0D43",  # mdi-air-filter
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F03D7",  # mdi-package-variant-closed
      "\U000F07D6",  # mdi-led-strip
      "\U000F00AC",  # mdi-blinds-closed
      "\U000F1011",  # mdi-blinds-open
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F1087",  # mdi-router-network
      "\U000F036B",  # mdi-message-video
      "\U000F0614",  # mdi-application-outline
      "\U000F089E",  # mdi-battery
      "\U000F07DE",  # mdi-filament
      "\U000F0317",  # mdi-lan
      "\U000F1B20",  # mdi-desk-lamp-on
      "\U000F17F4",  # mdi-lightbulb-spot
      "\U000F0769",  # mdi-ceiling-light
      "\U000F070D",  # mdi-robot-vacuum
      "\U000F050F",  # mdi-thermometer
      "\U000F0502",  # mdi-television
      "\U000F0210",  # mdi-fan
      "\U000F0A72",  # mdi-solar-power
      "\U000F072A",  # mdi-washing-machine
      "\U000F0438",  # mdi-radiator
      "\U000F02DC",  # mdi-home
      "\U000F040E",  # mdi-play-pause
      "\U000F034E",  # mdi-map-marker
      "\U000F1B88",  # mdi-awning-outline
      "\U000F0D91",  # mdi-motion-sensor
      "\U000F0AAC",  # mdi-dishwasher
      "\U000F0241",  # mdi-flash
      "\U000F0143",  # mdi-chevron-up
      "\U000F0140",  # mdi-chevron-down
      "\U000F1A45",  # mdi-heat-wave
      "\U000F04DB",  # mdi-stop
      "\U000F0917",  # mdi-tumble-dryer
      "\U000F081C",  # mdi-door-open
      "\U000F1054",  # mdi-outdoor-lamp
      "\U000F021F",  # mdi-image
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  printer:        "\U000F042B"
  aircon:         "\U000F0D43"
  ledstrip:       "\U000F1051"
  led_strip_variant: "\U000F1051"
  package:        "\U000F03D7"
  lights:         "\U000F07D6"
  blinds_closed:  "\U000F00AC"
  blinds_open:    "\U000F1011"
  nightlight:     "\U000F1A4C"
  network:        "\U000F1087"
  videocall:      "\U000F036B"
  application:    "\U000F0614"
  battery:        "\U000F089E"
  filament:       "\U000F07DE"
  lan:            "\U000F0317"
  desk_lamp:      "\U000F1B20"
  spot_light:     "\U000F17F4"
  ceiling_light:  "\U000F0769"
  robot_vacuum:   "\U000F070D"
  thermometer:    "\U000F050F"
  television:     "\U000F0502"
  fan:            "\U000F0210"
  solar_power:    "\U000F0A72"
  washing_machine: "\U000F072A"
  radiator:       "\U000F0438"
  home:           "\U000F02DC"
  play_pause:     "\U000F040E"
  locate:         "\U000F034E"
  awning:         "\U000F1B88"
  motion_sensor:  "\U000F0D91"
  dishwasher:     "\U000F0AAC"
  flash:          "\U000F0241"
  chevron_up:     "\U000F0143"
  chevron_down:   "\U000F0140"
  heat_wave:      "\U000F1A45"
  stop:           "\U000F04DB"
  tumble_dryer:   "\U000F0917"
  door_open:      "\U000F081C"
  outdoor_lamp:   "\U000F1054"
  image:          "\U000F021F"
